spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: your git uri
          username: your username
          password: your password
          basedir: F:\ideaProjects\studyProjects\imc-vx-order\config.basedir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
