eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: EUREKA
#server:
#  port: 8761